# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nature Photography
email: vin.piotrowski@gmail.com
description: Nature and landscape photography from Alberta and Western Canada featuring photo galleries and blogs by Vincent Piotrowski
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nature-photography.ca/"

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate-v2

# Produces a cleaner folder structure when using categories
#permalink: /:year/:month/:title.html
#permalink: /:year/:month/:title.html


# Explicitly turn off the old code
#paginate: nil
#paginate_path:

# Pagination Settings
pagination:
  enabled: true
  per_page: 4
  permalink: '/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
